spring.application.name=ecommerce
spring.datasource.url=jdbc:h2:mem:tiendadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2 y Swagger UI
spring.h2.console.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Ejecución automática de schema.sql y data.sql
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true